var gColorPickerColors = {
 "groups":
  [
    [
        "noteRed1",
        "noteRed2",
        "noteRed3",
        "noteRed4",
        "noteRed5",
        "noteRed6",
        "noteRed7"
    ],
    [
        "noteBrown1",
        "noteBrown2",
        "noteBrown3",
        "noteBrown4",
        "noteBrown5",
        "noteBrown6",
        "noteBrown7"
    ],
    [
        "notePink1",
        "notePink2",
        "notePink3",
        "notePink4",
        "notePink5",
        "notePink6",
        "notePink7"
    ],
    [
        "noteBlue1",
        "noteBlue2",
        "noteBlue3",
        "noteBlue4",
        "noteBlue5",
        "noteBlue6",
        "noteBlue7"
    ],
    [
        "noteGreen1",
        "noteGreen2",
        "noteGreen3",
        "noteGreen4",
        "noteGreen5",
        "noteGreen6",
        "noteGreen7"
    ],
    [
        "noteYellow1",
        "noteYellow2",
        "noteYellow3",
        "noteYellow4",
        "noteYellow5",
        "noteYellow6",
        "noteYellow7"
    ],
    [
        "noteLightBlue1",
        "noteLightGreen1",
        "noteGray",
        "noteDarkGray",
        "noteBlack",
        "noteWhite"
    ],
    [
        "noteBlackout1",
        "noteBlackout2",
        "noteBlackout2",
        "noteBlackout2",
        "noteBlackout2",
        "noteBlackout2",
        "noteBlackout2",
    ]
  ]
};
