export const gThemes = {
    "Default": {
        "id": "Default",
        "caption": "Default",
        "noteRadius": "20%",
        "noteCornerShape":"round",
        "namedNoteRadius": "16%",
        "notePadding": "8pt",
        "cellSpacing": "6pt",
        "instrumentBackground": "#7C4700",
        "instrumentMargins": "1em",
        "nutColor": "#331e01",
        "rootColor": "green",
        "diamondsSize": "1.5rem",
        "diamondsColor": "pink",
        "doubleDiamondsColor": "gold",
        "diamondsBackgroundColor":"transparent",
        "singleNoteShrink": "5%",
        "singleNoteShadowColor": "#56fa00",
        "noteWhiteShadowColor": "aqua",
        "noteBlackShadowColor": "pink",
        "noteWhiteKeyShadowColor": "0 0 2pt 1pt pink",
        "noteBlackKeyShadowColor": "0 0 2pt 1pt cornflowerblue", 
        "noteWhiteKeyColor": "white",
        "noteBlackKeyColor": "#555",
        "noteWhiteKeySpecialColor": "SaddleBrown",
        "noteBlackKeySpecialColor": "#191919",
        "noteWhiteKeyFontColor": "black",
        "noteBlackKeyFontColor": "white",
        "borderImageWhiteKey": "none",
        "borderImageBlackKey": "none"
    },
    "PoolShark" : {
        "id": "PoolShark",
        "caption":"Pool Shark",
        "noteRadius": "8%",
        "namedNoteRadius": "8%",
        "notePadding": "8pt",
        "cellSpacing": "0.5pt",
        "instrumentBackground": "DarkGreen",
        "nutColor": "lightgreen",
        "rootColor": "lightgreen",
        "diamondsColor": "red",
        "doubleDiamondsColor": "red",
        "diamondsSize": "1.0rem",
        "instrumentMargins": "2em",
        "noteWhiteShadowColor": "#222",
        "noteBlackShadowColor": "black",
        "noteWhiteKeyColor": "white",
        "noteBlackKeyColor": "#555",
        "noteWhiteKeyFontColor": "#555",
        "noteBlackKeyFontColor": "white",
        "instrumentBorderImage": "url('img/celtic-background-black.png')",
        "instrumentBorderThickness": "1em"
    },
    "Mahjong" : {
        "id": "Mahjong",
        "caption":"Mahjong",
        "noteRadius": "12%",
        "noteCornerShape": "bevel",
        "namedNoteRadius": "8%",
        "notePadding": "8pt",
        "cellSpacing": "1pt",
        "instrumentBackground": "DarkGreen",
        "instrumentMargins": "2em",
        "nutColor": "lightgreen",
        "rootColor": "lightgreen",
        "diamondsSize": "1.0rem",
        "diamondsColor": "red",
        "doubleDiamondsColor": "red",
        "diamondsBackgroundColor": "transparent",
        "singleNoteShrink": "5%",
        "singleNoteShadowColor": "#56fa00",
        "noteWhiteShadowColor": "#222",
        "noteBlackShadowColor": "black",
        "noteWhiteKeyShadowColor": "0 0 2pt 1pt pink",
        "noteBlackKeyShadowColor": "0 0 2pt 1pt pink",
        "noteWhiteKeyColor": "white",
        "noteBlackKeyColor": "#555",
        "noteWhiteKeySpecialColor": "SaddleBrown",
        "noteBlackKeySpecialColor": "#191919",
        "noteWhiteKeyFontColor": "#555",
        "noteBlackKeyFontColor": "white",
        "borderImageWhiteKey": "none",
        "borderImageBlackKey": "none",
        "instrumentBorderImage": "url('img/celtic-background-black.png')",
        "instrumentBorderThickness": "1.4em"
    },
    "Zinfandel" : {
        "id": "Zinfandel",
        "caption":"Zinfandel",
        "noteRadius": "8%",
        "namedNoteRadius": "8%",
        "notePadding": "8pt",
        "cellSpacing": "6pt",
        "instrumentBackground": "#311900",
        "nutColor": "brown",
        "diamondsSize": "0.6rem",
        "diamondsColor": "red",
        "doubleDiamondsColor": "orange",
        "diamondsBackgroundColor":"black",
        "instrumentBorderImage": "url('img/celtic-background-black.png')",
        "instrumentBorderThickness": "0.4em"
    },
    "Autobahn" : {
        "id": "Autobahn",
        "caption":"Autobahn",
        "noteRadius": "4%",
        "namedNoteRadius": "4%",
        "notePadding": "6pt",
        "cellSpacing": "5pt",
        "instrumentBackground": "black",
        "nutColor": "#ab0000",
        "diamondsColor": "green",
        "doubleDiamondsColor": "red",
        "noteWhiteShadowColor": "black",
        "noteBlackShadowColor": "black"
    },
    "LateNite" : {
        "id": "LateNite",
        "caption":"Late Nite",
        "noteRadius": "12%",
        "namedNoteRadius": "10%",
        "notePadding": "12pt",
        "cellSpacing": "7pt",
        "instrumentBackground": "#011d48",
        "nutColor": "#ab0000",
        "diamondsColor": "aqua",
        "doubleDiamondsColor": "gold",
        "noteWhiteKeyColor": "#f5e0c4",
        "noteBlackKeyColor": "#331e01",
        "noteWhiteKeyFontColor": "#331e01",
        "noteBlackKeyFontColor": "#f5e0c4"
    },
    "RobinHood": {
      "id": "RobinHood",
      "caption": "Robin Hood ",
      "noteRadius": "2%",
      "namedNoteRadius": "4%",
      "notePadding": "14pt",
      "cellSpacing": "8pt",
      "instrumentBackground": "#7C4700",
      "instrumentMargins": "0",
      "nutColor": "#331e01",
      "diamondsSize": "2rem",
      "diamondsColor": "green",
      "doubleDiamondsColor": "red",
      "diamondsBackgroundColor": "transparent",
      "noteWhiteShadowColor": "aqua",
      "noteBlackShadowColor": "pink",
      "noteWhiteKeyColor": "lightgreen",
      "noteBlackKeyColor": "#362312",
            "noteWhiteKeyFontColor": "#362312",
            "noteBlackKeyFontColor": "lightgreen",
      "borderImageWhiteKey": "url('img/celtic-background-white.png')",
      "borderImageBlackKey": "url('img/celtic-background-black.png')",
      "instrumentBorderImage": "url('img/celtic-background-black.png')"
    },
    "Shire" : {
        "id": "Shire",
        "caption":"Shire",
        "instrumentBackground": "#7C4700",
        "nutColor": "#331e01",
        "noteWhiteKeyColor": "lightgreen",
        "noteBlackKeyColor": "#362312",
        "noteWhiteKeyFontColor": "#362312",
        "noteBlackKeyFontColor": "lightgreen",
        "borderImageWhiteKey": "url('img/celtic-background-white.png')",
        "borderImageBlackKey":  "url('img/celtic-background-black.png')",
        "instrumentBorderImage": "url('img/celtic-background-black.png')",
        "instrumentBorderThickness": "0.4em"
    },
    "Renfaire" : {
        "id": "Renfaire",
        "caption":"Renfaire",
        "noteRadius": "12%",
        "namedNoteRadius": "10%",
        "notePadding": "18pt",
        "cellSpacing": "7pt",
        "instrumentBackground": "SaddleBrown",
        "nutColor": "#331e01",
        "noteWhiteKeyColor": "#f5e0c4",
        "noteBlackKeyColor": "#331e01",
        "noteWhiteKeyFontColor": "#331e01",
        "noteBlackKeyFontColor": "#f5e0c4",
        "borderImageWhiteKey": "url('img/celtic-background-2.png')",
        "borderImageBlackKey":  "url('img/celtic-background-2.png')",
        "instrumentBorderImage": "url('img/celtic-background-black.png')",
        "instrumentBorderThickness": "0.4em"
    },
    "LandauTop" : {
        "id": "LandauTop",
        "caption":"Landau Top",
        "noteRadius": "12%",
        "namedNoteRadius": "10%",
        "notePadding": "12pt",
        "cellSpacing": "7pt",
        "instrumentBackground": "SaddleBrown",
        "nutColor": "#331e01",
        "noteWhiteKeyColor": "#f5e0c4",
        "noteBlackKeyColor": "#331e01",
        "noteWhiteKeyFontColor": "#331e01",
        "noteBlackKeyFontColor": "#f5e0c4",
        "borderImageWhiteKey": "none"
    },
    "CoffyBrown" : {
        "id": "CoffyBrown",
        "caption":"Coffy Brown",
        "noteRadius": "12%",
        "namedNoteRadius": "10%",
        "notePadding": "12pt",
        "cellSpacing": "7pt",
        "instrumentBackground": "SaddleBrown",
        "nutColor": "#331e01",
        "noteWhiteShadowColor": "pink",
        "noteBlackShadowColor": "pink",
        "noteWhiteKeyShadowColor": "0 0 2pt 1pt pink",
        "noteBlackKeyShadowColor": "0 0 2pt 1pt pink",
        "noteWhiteKeyColor": "#331e01",
        "noteBlackKeyColor": "#331e01",
        "noteWhiteKeySpecialColor": "SaddleBrown",
        "noteBlackKeySpecialColor": "SaddleBrown",
        "noteWhiteKeyFontColor": "#f5e0c4",
        "noteBlackKeyFontColor": "#f5e0c4"
    },
    "Blade" : {
        "id": "Blade",
        "caption":"Blade",
        "noteRadius": "45%",
        "noteCornerShape":"bevel",
        "namedNoteRadius": "10%",
        "notePadding": "12pt",
        "cellSpacing": "7pt",
        "instrumentBackground": "black",
        "nutColor": "#331e01",
        "noteWhiteKeyShadowColor": "0 0 2pt 1pt red",
        "noteBlackKeyShadowColor": "0 0 2pt 1pt #311900",
        "noteWhiteKeyColor": "white",
        "noteBlackKeyColor": "black",
        "noteWhiteKeyFontColor": "black",
        "noteBlackKeyFontColor": "white",
        "borderImageWhiteKey":  "none",
        "borderImageBlackKey":  "none",
        "instrumentBorderImage": "url('img/blade-border.png')",
        "instrumentBorderThickness": "1.4em"
    },
    "Piano" : {
        "id": "Piano",
        "caption":"Piano",
        "noteRadius": "12%",
        "namedNoteRadius": "10%",
        "notePadding": "12pt",
        "cellSpacing": "7pt",
        "instrumentBackground": "black",
        "nutColor": "black",
        "noteWhiteKeyColor": "white",
        "noteBlackKeyColor": "black",
        "noteWhiteKeyFontColor": "black",
        "noteBlackKeyFontColor": "white"
    },
    "Reverse" : {
        "id": "Reverse",
        "caption":"Reverse",
        "noteRadius": "12%",
        "namedNoteRadius": "10%",
        "notePadding": "12pt",
        "cellSpacing": "7pt",
        "instrumentBackground": "black",
        "nutColor": "black",
        "noteWhiteKeyColor": "black",
        "noteBlackKeyColor": "white",
        "noteWhiteKeyFontColor": "white",
        "noteBlackKeyFontColor": "black"
    },
    "Snow" : {
        "id": "Snow",
        "caption":"Snow",
        "noteRadius": "12%",
        "namedNoteRadius": "10%",
        "notePadding": "12pt",
        "cellSpacing": "0.5pt",
        "instrumentBackground": "white",
        "nutColor": "white",
        "noteWhiteShadowColor": "gray",
        "noteBlackShadowColor": "gray",
        "noteWhiteKeyShadowColor": "0 0 2pt 1pt lightgray",
        "noteBlackKeyShadowColor": "0 0 2pt 1pt lightgray",
        "noteWhiteKeyColor": "white",
        "noteBlackKeyColor": "white",
        "noteWhiteKeyFontColor": "black",
        "noteBlackKeyFontColor": "black",
        "borderImageWhiteKey": "none"
    },
    "WiteOut" : {
        "id": "WiteOut",
        "caption":"Wite-Out",
        "noteRadius": "0",
        "namedNoteRadius": "10%",
        "notePadding": "12pt",
        "cellSpacing": "0.5pt",
        "instrumentBackground": "white",
        "nutColor": "white",
        "noteWhiteShadowColor": "white",
        "noteBlackShadowColor": "white",
        "noteWhiteKeyShadowColor": "0 0 2pt 1pt white",
        "noteBlackKeyShadowColor": "0 0 2pt 1pt white",
        "noteWhiteKeyColor": "white",
        "noteBlackKeyColor": "white",
        "noteWhiteKeyFontColor": "black",
        "noteBlackKeyFontColor": "black"
    },
    "Matrix" : {
        "id": "Matrix",
        "caption":"Matrix",
        "noteRadius": "12%",
        "namedNoteRadius": "10%",
        "notePadding": "12pt",
        "cellSpacing": "3pt",
        "instrumentBackground": "black",
        "nutColor": "white",
        "noteWhiteShadowColor": "chartreuse",
        "noteBlackShadowColor": "chartreuse",
        "noteWhiteKeyShadowColor": "0 0 2pt 1pt chartreuse",
        "noteBlackKeyShadowColor": "0 0 2pt 1pt chartreuse",
        "noteWhiteKeyColor": "black",
        "noteBlackKeyColor": "black",
        "noteWhiteKeyFontColor": "chartreuse",
        "noteBlackKeyFontColor": "chartreuse"
    },
    "Blackout" : {
        "id": "Blackout",
        "caption":"Blackout",
        "noteRadius": "12%",
        "namedNoteRadius": "10%",
        "notePadding": "12pt",
        "cellSpacing": "0.5pt",
        "instrumentBackground": "black",
        "nutColor": "white",
        "noteWhiteShadowColor": "black",
        "noteBlackShadowColor": "black",
        "noteWhiteKeyShadowColor": "0 0 2pt 1pt black",
        "noteBlackKeyShadowColor": "0 0 2pt 1pt black",
        "noteWhiteKeyColor": "black",
        "noteBlackKeyColor": "black",
        "noteWhiteKeyFontColor": "white",
        "noteBlackKeyFontColor": "white"
    },
    "AdultSwim" : {
        "id": "AdultSwim",
        "caption":"Adult Swim",
        "noteRadius": "20%",
        "namedNoteRadius": "18%",
        "notePadding": "6pt",
        "cellSpacing": "6pt",
        "instrumentBackground": "#0aa",
        "nutColor": "yellow",
        "diamondsColor": "pink",
        "diamondsSize": "3rem",
        "doubleDiamondsColor": "gold",
        "diamondsBackgroundColor":"transparent",
        "noteWhiteShadowColor": "green",
        "noteBlackShadowColor": "pink"
    },

    "EveryoneintothePool" : {
        "id": "EveryoneintothePool",
        "caption":"Everyone into the Pool",
        "noteRadius": "35%",
        "namedNoteRadius": "14%",
        "notePadding": "12pt",
        "cellSpacing": "6pt",
        "instrumentBackground": "#6ebcff",
        "nutColor": "yellow",
        "diamondsSize": "2rem",
        "diamondsColor": "darkblue",
        "doubleDiamondsColor": "red",
        "diamondsBackgroundColor":"transparent"
    },
    "DJTrailMix" : {
        "id": "DJTrailMix",
        "caption":"DJ TrailMix",
        "noteRadius": "8%",
        "namedNoteRadius": "8%",
        "notePadding": "12pt",
        "cellSpacing": "10pt",
        "instrumentBackground": "#333",
        "nutColor": "lightgray",
        "diamondsColor": "red",
        "doubleDiamondsColor": "red",
        "diamondsSize": "1.0rem",
        "instrumentMargins": "2em",
        "noteWhiteShadowColor": "#222",
        "noteBlackShadowColor": "black",
        "noteWhiteKeyColor": "aqua",
        "noteBlackKeyColor": "#555",
        "noteWhiteKeyFontColor": "#555",
        "noteBlackKeyFontColor": "aqua"
    },
    "BiginJapan" : {
        "id": "BiginJapan",
        "caption":"Big in Japan",
        "noteRadius": "45%",
        "namedNoteRadius": "10%",
        "notePadding": "12pt",
        "cellSpacing": "10pt",
        "instrumentBackground": "brown",
        "nutColor": "yellow",
        "diamondsSize": "4rem"
    },
    "GuitarStrings" : {
        "id": "GuitarStrings",
        "caption": "Guitar",
        "noteRadius": "0",
        "namedNoteRadius": "10%",
        "notePadding": "6pt",
        "cellSpacing": "0.1pt",
        "instrumentBackground": "SaddleBrown",
        "instrumentMargins": "1em",
        "nutColor": "#331e01",
        "diamondsSize": "1.5rem",
        "diamondsColor": "pink",
        "doubleDiamondsColor": "gold",
        "diamondsBackgroundColor": "transparent",
        "noteWhiteShadowColor": "#1a0000",
        "noteBlackShadowColor": "black",
        "noteWhiteKeyShadowColor": "0 0 2pt 1pt #ffab3c",
        "noteBlackKeyShadowColor": "0 0 2pt 1pt #170803",
        "noteWhiteKeyColor": "#ffab3c",
        "noteBlackKeyColor": "#170803",
        "noteWhiteKeySpecialColor": "SaddleBrown",
        "noteBlackKeySpecialColor": "#191919",
        "noteWhiteKeyFontColor": "#331e01",
        "noteBlackKeyFontColor": "#f5e0c4",
        "borderImageWhiteKey": "url('img/guitar-string-fret.png')",
        "borderImageBlackKey": "url('img/guitar-string-fret.png')",
        "instrumentBorderImage": "none",
        "instrumentBorderThickness": "0.2em"
    },
    "GuitarStringsGlow" : {
        "id": "GuitarStringsGlow",
        "caption": "Guitar Glow",
        "noteRadius": "0",
        "namedNoteRadius": "10%",
        "notePadding": "6pt",
        "cellSpacing": "0.1pt",
        "instrumentBackground": "SaddleBrown",
        "instrumentMargins": "1em",
        "nutColor": "#331e01",
        "diamondsSize": "1.5rem",
        "diamondsColor": "pink",
        "doubleDiamondsColor": "gold",
        "diamondsBackgroundColor": "transparent",
        "noteWhiteShadowColor": "aqua",
        "noteBlackShadowColor": "pink",
        "noteWhiteKeyShadowColor": "0 0 2pt 1pt #ffab3c",
        "noteBlackKeyShadowColor": "0 0 2pt 1pt #170803",
        "noteWhiteKeyColor": "#ffab3c",
        "noteBlackKeyColor": "#170803",
        "noteWhiteKeySpecialColor": "SaddleBrown",
        "noteBlackKeySpecialColor": "#191919",
        "noteWhiteKeyFontColor": "#331e01",
        "noteBlackKeyFontColor": "#f5e0c4",
        "borderImageWhiteKey": "url('img/guitar-string-fret.png')",
        "borderImageBlackKey": "url('img/guitar-string-fret.png')",
        "instrumentBorderImage": "none",
        "instrumentBorderThickness": "0.2em"
    },
    "GuitarStringsBlack": {
        "id": "GuitarStringsBlack",
        "caption": "Guitar Black",
        "noteRadius": "0",
        "namedNoteRadius": "10%",
        "notePadding": "6pt",
        "cellSpacing": "0.1pt",
        "instrumentBackground": "#311900",
        "instrumentMargins": "0",
        "nutColor": "brown",
        "diamondsSize": "1.5rem",
        "diamondsColor": "pink",
        "doubleDiamondsColor": "gold",
        "diamondsBackgroundColor": "transparent",
        "noteWhiteShadowColor": "black",
        "noteBlackShadowColor": "black",
        "noteWhiteKeyShadowColor": "0 0 2pt 1pt black",
        "noteBlackKeyShadowColor": "0 0 2pt 1pt black",
        "noteWhiteKeyColor": "black",
        "noteBlackKeyColor": "black",
        "noteWhiteKeySpecialColor": "SaddleBrown",
        "noteBlackKeySpecialColor": "#191919",
        "noteWhiteKeyFontColor": "white",
        "noteBlackKeyFontColor": "white",
        "borderImageWhiteKey": "url('img/guitar-string-fret.png')",
        "borderImageBlackKey": "url('img/guitar-string-fret.png')",
        "instrumentBorderImage": "url('img/celtic-background-black.png')",
        "instrumentBorderThickness": "0.4em"
    },
    "GuitarStringsBlackGlow": {
        "id": "GuitarStringsBlackGlow",
        "caption": "Guitar Black Glow",
        "noteRadius": "0",
        "namedNoteRadius": "10%",
        "notePadding": "6pt",
        "cellSpacing": "0.1pt",
        "instrumentBackground": "#311900",
        "instrumentMargins": "0",
        "nutColor": "brown",
        "diamondsSize": "1.5rem",
        "diamondsColor": "pink",
        "doubleDiamondsColor": "gold",
        "diamondsBackgroundColor": "transparent",
        "noteWhiteShadowColor": "aqua",
        "noteBlackShadowColor": "pink",
        "noteWhiteKeyShadowColor": "0 0 2pt 1pt black",
        "noteBlackKeyShadowColor": "0 0 2pt 1pt black",
        "noteWhiteKeyColor": "black",
        "noteBlackKeyColor": "black",
        "noteWhiteKeySpecialColor": "SaddleBrown",
        "noteBlackKeySpecialColor": "#191919",
        "noteWhiteKeyFontColor": "white",
        "noteBlackKeyFontColor": "white",
        "borderImageWhiteKey": "url('img/guitar-string-fret.png')",
        "borderImageBlackKey": "url('img/guitar-string-fret.png')",
        "instrumentBorderImage": "url('img/celtic-background-black.png')"
    },
    "GuitarStringsWhite": {
        "id": "GuitarStringsWhite",
        "caption": "Guitar White",
        "noteRadius": "0",
        "namedNoteRadius": "10%",
        "notePadding": "6pt",
        "cellSpacing": "0.1pt",
        "instrumentBackground": "#230404",
        "instrumentMargins": "0",
        "nutColor": "green",
        "diamondsSize": "1.5rem",
        "diamondsColor": "brown",
        "doubleDiamondsColor": "gold",
        "diamondsBackgroundColor": "black",
        "noteWhiteShadowColor": "black",
        "noteBlackShadowColor": "black",
        "noteWhiteKeyShadowColor": "0 0 2pt 1pt white",
        "noteBlackKeyShadowColor": "0 0 2pt 1pt white",
        "noteWhiteKeyColor": "white",
        "noteBlackKeyColor": "white",
        "noteWhiteKeySpecialColor": "SaddleBrown",
        "noteBlackKeySpecialColor": "#191919",
        "noteWhiteKeyFontColor": "black",
        "noteBlackKeyFontColor": "black",
        "borderImageWhiteKey": "url('img/guitar-string-fret.png')",
        "borderImageBlackKey": "url('img/guitar-string-fret.png')",
        "instrumentBorderImage": "url('img/celtic-background-black.png')"
    },
    "USER" : {
        "id": "USER",
        "caption": "USER"
    }
}
