var allTunings = {
    "tunings" : [
	      {
            "baseID": "P48",
            "baseInstrument":"Guitar",
            "caption": "P4-8",
            "nStrings": 8,
            "rowRange" : [65,60,55,50,45,40,35,30],
            "diamonds" : [3,5,7,9,15,17,19,21],
            "doubleDiamonds" : [12,24],
            "stringDividerHeight": "0.6em",
            "frets" : 24,
            "nut" : true,
            "reverse" : false,
            "visible" : false
	       },
	       {
            "baseID": "P46",
            "baseInstrument":"Guitar",
            "caption": "P4",
            "nStrings": 6,
            "rowRange" : [65,60,55,50,45,40],
            "diamonds" : [3,5,7,9,15,17,19,21],
            "doubleDiamonds" : [12,24],
            "frets" : 24,
            "nut" : true,
            "reverse" : false,
            "visible" : true
	       },
	       {
            "baseID": "S6",
            "baseInstrument":"Guitar",
            "caption": "Standard",
            "nStrings": 6,
            "rowRange" : [64,59,55,50,45,40],
            "diamonds" : [3,5,7,9,15,17,19,21],
            "doubleDiamonds" : [12,24],
            "frets" : 16,
            "nut" : true,
            "reverse" : false,
            "visible" : false
	       },
	       {
            "baseID": "S8",
            "baseInstrument":"Guitar",
            "caption": "Standard-8",
            "nStrings": 8,
            "rowRange" : [64,59,55,50,45,40,35,30],   //120=C9
            "diamonds" : [3,5,7,9,15,17,19,21],
            "doubleDiamonds" : [12,24],
            "frets" : 16,
            "nut" : true,
            "reverse" : false,
            "visible" : false,
            "pianoNamesRow" : true
	       },
	       {
            "baseID": "DropD",
            "baseInstrument":"Guitar",
            "caption": "DropD",
            "nStrings": 6,
            "rowRange" : [64,59,55,50,45,38],
            "diamonds" : [3,5,7,9,15,17,19,21],
            "doubleDiamonds" : [12,24],
            "frets" : 18,
            "nut" : true,
            "reverse" : false,
            "visible" : false
	       },
	       {
            "baseID": "DADGAD",
            "baseInstrument":"Guitar",
            "caption": "DADGAD",
            "nStrings": 6,
            "rowRange" : [62,57,55,50,45,38],   //120=C9
            "diamonds" : [3,5,7,9,15,17,19,21],
            "doubleDiamonds" : [12,24],
            "frets" : 16,
            "nut" : true,
            "reverse" : false,
            "visible" : false
	       },
	       {
            "baseID": "DGDGBD",
            "baseInstrument":"Guitar",
            "caption": "DGDGBD",
            "nStrings": 6,
            "rowRange" : [62,59,55,50,43,38],
            "diamonds" : [3,5,7,9,15,17,19,21],
            "doubleDiamonds" : [12,24],
            "frets" : 16,
            "nut" : true,
            "reverse" : false,
            "visible" : false
	       },
           {
             "baseID": "Bass4",
             "baseInstrument":"Bass",
             "caption": "Bass",
             "nStrings": 4,
             "rowRange" : [43,38,33,28],
             "diamonds" : [3,5,7,9,15,17,19,21],
             "doubleDiamonds" : [12,24],
             "stringDividerHeight": "0.6em",
             "frets" : 15,
             "nut" : true,
             "reverse" : false,
             "visible" : false
 	       },
	       {
             "baseID": "Bass8",
             "baseInstrument":"Bass",
             "caption": "Bass 8",
             "nStrings": 8,
             "rowRange" : [58,53,48,43,38,33,28,23],
             "diamonds" : [3,5,7,9,15,17,19,21],
             "doubleDiamonds" : [12,24],
             "stringDividerHeight": "0.6em",
             "frets" : 16,
             "nut" : true,
             "reverse" : false,
             "visible" : false
 	       },
           {
             "baseID": "Cello",
             "baseInstrument":"Cello",
             "caption": "Cello",
             "nStrings": 4,
             "rowRange" : [57,50,43,36],
             "diamonds" : [],
             "doubleDiamonds" : [],
             "stringDividerHeight": "0",
             "frets" : 16,
             "nut" : true,
             "reverse" : false,
             "visible" : false
 	       },
           {
              "baseID": "UkuleleSoprano",
              "baseInstrument":"Ukulele",
              "caption": "Soprano Ukulele",
              "nStrings": 4,
              "rowRange" : [69,67,64,72],
              "diamonds" : [5,7,10],
              "stringDividerHeight": "0",
              "frets" : 15,
              "nut" : true,
              "reverse" : false,
              "visible" : false
            },
            {
              "baseID": "UkuleleConcert",
              "baseInstrument":"Ukulele",
              "caption": "Concert Ukulele",
              "nStrings": 4,
              "rowRange" : [69,67,64,72],
              "diamonds" : [5,7,10,15],
              "doubleDiamonds" : [12],
              "stringDividerHeight": "0",
              "frets" : 20,
              "nut" : true,
              "reverse" : false,
              "visible" : false
            },
            {
              "baseID": "UkuleleTenor",
              "baseInstrument":"Ukulele",
              "caption": "Tenor Ukulele",
              "nStrings": 4,
              "rowRange" : [69,67,64,60],
              "diamonds" : [5,7,10,15],
              "doubleDiamonds" : [12],
              "stringDividerHeight": "0",
              "frets" : 22,
              "nut" : true,
              "reverse" : false,
              "visible" : false
            },
            {
              "baseID": "UkuleleBaritone",
              "baseInstrument":"Ukulele",
              "caption": "Baritone Ukulele",
              "nStrings": 4,
              "rowRange" : [64,59,55,50],
              "diamonds" : [5,7,10,15],
              "doubleDiamonds" : [12],
              "stringDividerHeight": "0",
              "frets" : 22,
              "nut" : true,
              "reverse" : false,
              "visible" : false
            },
           {
             "baseID": "Mandolin",
             "baseInstrument":"Mandolin",
             "caption": "Mandolin",
             "nStrings": 4,
             "rowRange" : [76,69,62,55],
             "diamonds" : [5,7,10,15],
             "doubleDiamonds" : [12],
             "stringDividerHeight": "0",
             "frets" : 20,
             "nut" : true,
             "reverse" : false,
             "visible" : false
 	       },
           {
            "baseID": "BanjoG",
            "baseInstrument":"Banjo",
            "caption": "Banjo Open G",
            "nStrings": 5,
            "rowRange" : [62,59,55,50,62],
            "frets" : 17,
            "nut" : true,
            "banjoNut": {4: 5}, /* dictionary: {stringnum:nutfretnum, stringnum:nutfretnum, ...} like {4:5, 5:6} puts nuts on 4th string at 5th nut plus 5th string at 6th nut. */
            "reverse" : false,
            "visible" : false
	       },
           {
            "baseID": "BanjoDoubleD",
            "baseInstrument":"Banjo",
            "caption": "Banjo Double D",
            "nStrings": 5,
            "rowRange" : [62,60,55,48,64],
            "frets" : 17,
            "nut" : true,
            "banjoNut": {0: 2, 1: 2, 2: 2, 3: 2, 4: 5}, /* dictionary: {stringnum:nutfretnum, stringnum:nutfretnum, ...} like {4:5, 5:6} puts nuts on 4th string at 5th nut plus 5th string at 6th nut. */
            "reverse" : false,
            "visible" : false
	       },

           {
            "baseID": "BanjoDoubleC",
            "baseInstrument":"Banjo",
            "caption": "Banjo Double C",
            "nStrings": 5,
            "rowRange" : [62,60,55,48,62],
            "frets" : 17,
            "nut" : true,
            "banjoNut": {4: 5}, /* dictionary: {stringnum:nutfretnum, stringnum:nutfretnum, ...} like {4:5, 5:6} puts nuts on 4th string at 5th nut plus 5th string at 6th nut. */
            "reverse" : false,
            "visible" : false
	       },
           {
            "baseID": "BanjoSawmill",
            "baseInstrument":"Banjo",
            "caption": "Banjo Sawmill",
            "nStrings": 5,
            "rowRange" : [62,60,55,50,62],
            "frets" : 17,
            "nut" : true,
            "banjoNut": {4: 5}, /* dictionary: {stringnum:nutfretnum, stringnum:nutfretnum, ...} like {4:5, 5:6} puts nuts on 4th string at 5th nut plus 5th string at 6th nut. */
            "reverse" : false,
            "visible" : false
	       },
           {
             "baseID": "BanjoGraveyard",
             "baseInstrument":"Banjo",
             "caption": "Banjo Graveyard [D]",
             "nStrings": 5,
             "rowRange" : [62,57,54,50,64],
             "frets" : 17,
             "nut" : true,
             "banjoNut": {4: 5}, /* dictionary: {stringnum:nutfretnum, stringnum:nutfretnum, ...} like {4:5, 5:6} puts nuts on 4th string at 5th nut plus 5th string at 6th nut. */
             "reverse" : false,
             "visible" : false
           },
	       {
            "baseID": "Perfect4thsCalculator",
            "baseInstrument":"Guitar",
            "caption": "Perfect 4ths Calculator",
            "nStrings": 17,
            "rowRange" : [110,105,100,95,90,85,80,75,70,65,60,55,50,45,40,35,30],
            "frets" : 1,
            "nut" : false,
            "reverse" : false,
            "visible" : false
	       },
           {
            "baseID": "TritoneCalculator",
            "baseInstrument":"Guitar",
            "caption": "Tritone Calculator",
            "nStrings": 6,
            "rowRange" : [58,52,46,40,34,28],
            "frets" : 24,
            "nut" : false,
            "reverse" : false,
            "visible" : false
	       },
	       {
           "baseID": "ThirdsCalculator",
           "baseInstrument":"Guitar",
           "caption": "ThirdsCalculator",
           "nStrings": 8,
           "rowRange" : [56,52,48,44,40,36,32,28],
           "frets" : 24,
           "nut" : false,
           "reverse" : false,
           "visible" : false
           },
           {
            "baseID": "Chapman10Classic",
            "baseInstrument":"ChampmanStick",
            "caption": "Classic 10",
            "nStrings": 10,
            "rowRange" : [62,57,52,47,42, 24,31,38,45,52],
            "frets" : 24,
            "nut" : true,
            "reverse" : false,
            "visible" : false
	       },
	       {
            "baseID": "MIDI",
            "baseInstrument":"MIDI",
            "caption": "8x8",
            "nStrings": 8,
            "rowRange" : [71,66,61,56,51,46,41,36],
            "frets" : 8,
            "nut" : false,
            "leftmargin" : true,
            "reverse" : false,
            "visible" : false,
            "fixedFretWidth" : true,
            "pinkKey": "C"
           },
           {
            "baseID": "Linstrument",
            "baseInstrument":"MIDI",
            "caption": "Linstrument 8x24",
            "nStrings": 8,
            "rowRange" : [71,66,61,56,51,46,41,36],
            "frets" : 24,
            "nut" : false,
            "leftmargin" : true,
            "reverse" : false,
            "visible" : false,
            "fixedFretWidth" : true,
            "pinkKey": "C"
           },
           {
             "baseID": "DEV",
             "baseInstrument":"Guitar",
             "caption": "Developer",
             "nStrings": 1,
             "rowRange" : [65],
             "frets" : 2,
             "nut" : false,
             "reverse" : false,
             "visible" : false
 	       },
           {
            "baseID": "PianoFrets",
            "baseInstrument":"Piano",
            "caption": "Piano Guitar",
            "nStrings": 2,
            "rowRange" : [36],
            "frets" : 88,
            "nut" : false,
            "reverse" : false,
            "visible" : false,
            "pianoNamesRow" : true
           },
           {
            "baseID": "PianoFrets2",
            "baseInstrument":"Piano",
            "caption": "Piano Guitar 2Row",
            "nStrings": 2,
            "rowRange" : [48, 36],
            "frets" : 49,
            "nut" : false,
            "reverse" : false,
            "visible" : false,
            "pianoNamesRow" : true
           },
           {
            "baseID": "PianoFretsBass",
            "baseInstrument":"Piano",
            "caption": "Piano Bass",
            "nStrings": 1,
            "rowRange" : [23],
            "frets" : 49,
            "nut" : false,
            "reverse" : false,
            "visible" : false,
            "pianoNamesRow" : true
           },
           {
            "baseID": "PianoSchroeder",
            "baseInstrument":"Piano",
            "caption": "Piano Schroeder",
            "nStrings": 1,
            "rowRange" : [48],
            "frets" : 26,
            "nut" : false,
            "reverse" : false,
            "visible" : false,
            "pianoNamesRow" : true,
            "fixedFretWidthMult" : 0.5
           },
           {
            "baseID": "Piano",
            "baseInstrument":"Piano",
            "caption": "Piano",
            "nStrings": 1,
            "rowRange" : [24],
            "frets" : 88,
            "nut" : false,
            "reverse" : false,
            "visible" : false,
            "pianoNamesRow" : true,
            "pianoNamesRowHeight" : "30pt",
            "fixedFretWidthMult" : 1.0
         }
	   ]
	};
