export const allTunings = {
  "tunings": [
    {
      "instance": false,
      "baseID": "P48",
      "baseInstrument": "Guitar",
      "caption": "P4-8",
      "nStrings": 8,
      "rowRange": [65, 60, 55, 50, 45, 40, 35, 30],
      "showDiamonds": true,
      "diamonds": [3, 5, 7, 9, 15, 17, 19, 21],
      "doubleDiamonds": [12, 24],
      "stringDividerHeight": "0",
      "frets": 24,
      "nut": true,
      "reverse": false,
    },
    {
      "instance": false,
      "baseID": "P46",
      "baseInstrument": "Guitar",
      "caption": "P4",
      "nStrings": 6,
      "rowRange": [65, 60, 55, 50, 45, 40],
      "showDiamonds": true,
      "diamonds": [3, 5, 7, 9, 15, 17, 19, 21],
      "doubleDiamonds": [12, 24],
      "frets": 24,
      "nut": true,
      "reverse": false,
    },
    {
      "instance": false,
      "baseID": "S6",
      "baseInstrument": "Guitar",
      "caption": "Standard",
      "nStrings": 6,
      "rowRange": [64, 59, 55, 50, 45, 40],
      "specialBackgroundIDRows": [0, 1],
      "doSpecialRows": true,
      "showDiamonds": true,
      "diamonds": [3, 5, 7, 9, 15, 17, 19, 21],
      "doubleDiamonds": [12, 24],
      "frets": 16,
      "nut": true,
      "reverse": false,
    },
    {
      "instance": false,
      "baseID": "S1",
      "baseInstrument": "Guitar",
      "caption": "OneString",
      "nStrings": 1,
      "rowRange": [40],
      "showDiamonds": true,
      "diamonds": [3, 5, 7, 9, 15, 17, 19, 21],
      "doubleDiamonds": [12, 24],
      "frets": 16,
      "nut": true,
      "reverse": false,
    },
    {
      "instance": false,
      "baseID": "S8",
      "baseInstrument": "Guitar",
      "caption": "Standard-8",
      "nStrings": 8,
      "rowRange": [64, 59, 55, 50, 45, 40, 35, 30],
      "specialBackgroundIDRows": [0, 1],
      "doSpecialRows": true,
      "showDiamonds": true,
      "diamonds": [3, 5, 7, 9, 15, 17, 19, 21],
      "doubleDiamonds": [12, 24],
      "frets": 16,
      "nut": true,
      "reverse": false,
      "pianoNamesRow": false
    },
    {
      "instance": false,
      "baseID": "DropD",
      "baseInstrument": "Guitar",
      "caption": "DropD",
      "nStrings": 6,
      "rowRange": [64, 59, 55, 50, 45, 38],
      "specialBackgroundIDRows": [0, 1, 5],
      "doSpecialRows": true,
      "showDiamonds": true,
      "diamonds": [3, 5, 7, 9, 15, 17, 19, 21],
      "doubleDiamonds": [12, 24],
      "frets": 18,
      "nut": true,
      "reverse": false,
    },
    {
      "instance": false,
      "baseID": "DADGAD",
      "baseInstrument": "Guitar",
      "caption": "DADGAD",
      "nStrings": 6,
      "rowRange": [62, 57, 55, 50, 45, 38],
      "specialBackgroundIDRows": [0, 1, 5],
      "doSpecialRows": true,
      "showDiamonds": true,
      "diamonds": [3, 5, 7, 9, 15, 17, 19, 21],
      "doubleDiamonds": [12, 24],
      "frets": 16,
      "nut": true,
      "reverse": false,
    },
    {
      "instance": false,
      "baseID": "DGDGBD",
      "baseInstrument": "Guitar",
      "caption": "DGDGBD",
      "nStrings": 6,
      "rowRange": [62, 59, 55, 50, 43, 38],
      "specialBackgroundIDRows": [0, 1, 4, 5],
      "doSpecialRows": true,
      "showDiamonds": true,
      "diamonds": [3, 5, 7, 9, 15, 17, 19, 21],
      "doubleDiamonds": [12, 24],
      "frets": 16,
      "nut": true,
      "reverse": false,
    },
    {
      "instance": false,
      "baseID": "Bass4",
      "baseInstrument": "Bass",
      "caption": "Bass",
      "nStrings": 4,
      "rowRange": [43, 38, 33, 28],
      "showDiamonds": true,
      "diamonds": [3, 5, 7, 9, 15, 17, 19, 21],
      "doubleDiamonds": [12, 24],
      "stringDividerHeight": "0",
      "frets": 15,
      "nut": true,
      "reverse": false,
    },
    {
      "instance": false,
      "baseID": "Bass5",
      "baseInstrument": "Bass",
      "caption": "Bass 5",
      "nStrings": 5,
      "rowRange": [43, 38, 33, 28, 23],
      "showDiamonds": true,
      "diamonds": [3, 5, 7, 9, 15, 17, 19, 21],
      "doubleDiamonds": [12, 24],
      "stringDividerHeight": "0",
      "frets": 16,
      "nut": true,
      "reverse": false,
    },
    {
      "instance": false,
      "baseID": "Bass6",
      "baseInstrument": "Bass",
      "caption": "Bass 6",
      "nStrings": 6,
      "rowRange": [48, 43, 38, 33, 28, 23],
      "showDiamonds": true,
      "diamonds": [3, 5, 7, 9, 15, 17, 19, 21],
      "doubleDiamonds": [12, 24],
      "stringDividerHeight": "0",
      "frets": 16,
      "nut": true,
      "reverse": false,
    },
    {
      "instance": false,
      "baseID": "Bass8",
      "baseInstrument": "Bass",
      "caption": "Bass 8",
      "nStrings": 8,
      "rowRange": [58, 53, 48, 43, 38, 33, 28, 23],
      "showDiamonds": true,
      "diamonds": [3, 5, 7, 9, 15, 17, 19, 21],
      "doubleDiamonds": [12, 24],
      "stringDividerHeight": "0",
      "frets": 16,
      "nut": true,
      "reverse": false,
    },
    {
      "instance": false,
      "baseID": "Cello",
      "baseInstrument": "Cello",
      "caption": "Cello",
      "nStrings": 4,
      "rowRange": [57, 50, 43, 36],
      "showDiamonds": false,
      "diamonds": [],
      "doubleDiamonds": [],
      "stringDividerHeight": "0",
      "frets": 16,
      "nut": true,
      "reverse": false,
    },
    {
      "instance": false,
      "baseID": "UkuleleSoprano",
      "baseInstrument": "Ukulele",
      "caption": "Soprano Ukulele",
      "nStrings": 4,
      "rowRange": [69, 67, 64, 72],
      "showDiamonds": true,
      "diamonds": [5, 7, 10],
      "stringDividerHeight": "0",
      "frets": 15,
      "nut": true,
      "reverse": false,
    },
    {
      "instance": false,
      "baseID": "UkuleleConcert",
      "baseInstrument": "Ukulele",
      "caption": "Concert Ukulele",
      "nStrings": 4,
      "rowRange": [69, 67, 64, 72],
      "showDiamonds": true,
      "diamonds": [5, 7, 10, 15],
      "doubleDiamonds": [12],
      "stringDividerHeight": "0",
      "frets": 20,
      "nut": true,
      "reverse": false,
    },
    {
      "instance": false,
      "baseID": "UkuleleTenor",
      "baseInstrument": "Ukulele",
      "caption": "Tenor Ukulele",
      "nStrings": 4,
      "rowRange": [69, 67, 64, 60],
      "showDiamonds": true,
      "diamonds": [5, 7, 10, 15],
      "doubleDiamonds": [12],
      "stringDividerHeight": "0",
      "frets": 22,
      "nut": true,
      "reverse": false,
    },
    {
      "instance": false,
      "baseID": "UkuleleBaritone",
      "baseInstrument": "Ukulele",
      "caption": "Baritone Ukulele",
      "nStrings": 4,
      "rowRange": [64, 59, 55, 50],
      "showDiamonds": true,
      "diamonds": [5, 7, 10, 15],
      "doubleDiamonds": [12],
      "stringDividerHeight": "0",
      "frets": 22,
      "nut": true,
      "reverse": false,
    },
    {
      "instance": false,
      "baseID": "Mandolin",
      "baseInstrument": "Mandolin",
      "caption": "Mandolin",
      "nStrings": 4,
      "rowRange": [76, 69, 62, 55],
      "showDiamonds": true,
      "diamonds": [5, 7, 10, 15],
      "doubleDiamonds": [12],
      "stringDividerHeight": "0",
      "frets": 20,
      "nut": true,
      "reverse": false,
    },
    {
      "instance": false,
      "baseID": "BanjoG",
      "baseInstrument": "Banjo",
      "caption": "Banjo Open G",
      "nStrings": 5,
      "rowRange": [62, 59, 55, 50, 62],
      "showDiamonds": true,
      "diamonds": [3, 5, 7, 10, 15, 17],
      "doubleDiamonds": [12],
      "frets": 17,
      "nut": true,
      "banjoNut": { "4": 5 },
      "reverse": false,
    },
    {
      "instance": false,
      "baseID": "BanjoDoubleD",
      "baseInstrument": "Banjo",
      "caption": "Banjo Double D",
      "nStrings": 5,
      "rowRange": [62, 60, 55, 48, 64],
      "showDiamonds": true,
      "diamonds": [3, 5, 7, 10, 15, 17],
      "doubleDiamonds": [12],
      "frets": 17,
      "nut": true,
      "banjoNut": { "0": 2, "1": 2, "2": 2, "3": 2, "4": 5 },
      "reverse": false,
    },
    {
      "instance": false,
      "baseID": "BanjoDoubleC",
      "baseInstrument": "Banjo",
      "caption": "Banjo Double C",
      "nStrings": 5,
      "rowRange": [62, 60, 55, 48, 62],
      "showDiamonds": true,
      "diamonds": [3, 5, 7, 10, 15, 17],
      "doubleDiamonds": [12],
      "frets": 17,
      "nut": true,
      "banjoNut": { "4": 5 },
      "reverse": false,
    },
    {
      "instance": false,
      "baseID": "BanjoSawmill",
      "baseInstrument": "Banjo",
      "caption": "Banjo Sawmill",
      "nStrings": 5,
      "rowRange": [62, 60, 55, 50, 62],
      "showDiamonds": true,
      "diamonds": [3, 5, 7, 10, 15, 17],
      "doubleDiamonds": [12],
      "frets": 17,
      "nut": true,
      "banjoNut": { "4": 5 },
      "reverse": false,
    },
    {
      "instance": false,
      "baseID": "BanjoGraveyard",
      "baseInstrument": "Banjo",
      "caption": "Banjo Graveyard [D]",
      "nStrings": 5,
      "rowRange": [62, 57, 54, 50, 64],
      "showDiamonds": true,
      "diamonds": [3, 5, 7, 10, 15, 17],
      "doubleDiamonds": [12],
      "frets": 17,
      "nut": true,
      "banjoNut": { "4": 5 },
      "reverse": false,
    },
    {
      "instance": false,
      "baseID": "Perfect4thsCalculator",
      "baseInstrument": "Guitar",
      "caption": "Perfect 4ths Calculator",
      "nStrings": 17,
      "rowRange": [110, 105, 100, 95, 90, 85, 80, 75, 70, 65, 60, 55, 50, 45, 40, 35, 30],
      "frets": 1,
      "nut": false,
      "reverse": false,
      "Tool": true
    },
    {
      "instance": false,
      "baseID": "Perfect5thsCalculator",
      "baseInstrument": "Guitar",
      "caption": "Perfect 5ths Calculator",
      "nStrings": 17,
      "rowRange": [125, 118, 111, 104, 97, 90, 93, 86, 79, 72, 65, 58, 51, 44, 37, 30],
      "frets": 1,
      "nut": false,
      "reverse": false,
      "Tool": true
    },
    {
      "instance": false,
      "baseID": "TritoneCalculator",
      "baseInstrument": "Guitar",
      "caption": "Tritone Calculator",
      "nStrings": 3,
      "rowRange": [58, 52, 46],
      "frets": 5,
      "nut": false,
      "reverse": false,
      "Tool": true
    },
    {
      "instance": false,
      "baseID": "ThirdsCalculator",
      "baseInstrument": "Guitar",
      "caption": "ThirdsCalculator",
      "nStrings": 4,
      "rowRange": [56, 52, 48, 44],
      "frets": 4,
      "nut": false,
      "reverse": false,
      "Tool": true
    },
    {
      "instance": false,
      "baseID": "Chapman10Classic",
      "baseInstrument": "ChampmanStick",
      "caption": "Classic 10",
      "nStrings": 10,
      "rowRange": [62, 57, 52, 47, 42, 24, 31, 38, 45, 52],
      "frets": 24,
      "nut": true,
      "reverse": false,
    },
    {
      "instance": false,
      "baseID": "MIDI",
      "baseInstrument": "MIDI",
      "caption": "8x8",
      "nStrings": 8,
      "rowRange": [71, 66, 61, 56, 51, 46, 41, 36],
      "frets": 8,
      "nut": false,
      "leftmargin": true,
      "reverse": false,
      "fixedFretWidth": true,
      "pinkKey": "C"
    },
    {
      "instance": false,
      "baseID": "MIDI-P4",
      "baseInstrument": "MIDI",
      "caption": "8x8-P4",
      "nStrings": 8,
      "rowRange": [65, 60, 55, 50, 45, 40, 35, 30],
      "frets": 8,
      "nut": false,
      "leftmargin": true,
      "reverse": false,
      "fixedFretWidth": true,
      "pinkKey": "C"
    },
    {
      "instance": false,
      "baseID": "Linstrument",
      "baseInstrument": "MIDI",
      "caption": "Linstrument 8x24",
      "nStrings": 8,
      "rowRange": [71, 66, 61, 56, 51, 46, 41, 36],
      "frets": 24,
      "nut": false,
      "leftmargin": true,
      "reverse": false,
      "fixedFretWidth": true,
      "pinkKey": "C"
    },
    {
      "instance": false,
      "baseID": "DEV",
      "baseInstrument": "Guitar",
      "caption": "Developer",
      "nStrings": 1,
      "rowRange": [65],
      "frets": 2,
      "nut": false,
      "reverse": false,
    },
    {
      "instance": false,
      "baseID": "PianoFrets",
      "baseInstrument": "Piano",
      "caption": "Piano Guitar",
      "nStrings": 1,
      "rowRange": [21],
      "frets": 88,
      "nut": false,
      "reverse": false,
      "pianoNamesRow": true
    },
    {
      "instance": false,
      "baseID": "PianoFrets2",
      "baseInstrument": "Piano",
      "caption": "Piano Guitar 2Row",
      "nStrings": 2,
      "rowRange": [48, 36],
      "frets": 49,
      "nut": false,
      "reverse": false,
      "pianoNamesRow": true
    },
    {
      "instance": false,
      "baseID": "PianoFretsBass",
      "baseInstrument": "Piano",
      "caption": "Piano Bass",
      "nStrings": 1,
      "rowRange": [21],
      "frets": 49,
      "nut": false,
      "reverse": false,
      "pianoNamesRow": true
    },
    {
      "instance": false,
      "baseID": "PianoSchroeder",
      "baseInstrument": "Piano",
      "caption": "Piano Schroeder",
      "nStrings": 1,
      "rowRange": [48],
      "frets": 26,
      "nut": false,
      "reverse": false,
      "pianoNamesRow": true,
      "fixedFretWidthMult": 0.5
    },
    {
      "instance": false,
      "baseID": "Piano",
      "baseInstrument": "Piano",
      "caption": "Piano",
      "nStrings": 1,
      "rowRange": [21],
      "frets": 88,
      "nut": false,
      "reverse": false,
      "pianoNamesRow": false,
      "pianoSkeuomorphic": true,
      "fixedFretWidthMult": 0.5
    },
    {
      "instance": false,
      "baseID": "Organ2Rows",
      "baseInstrument": "Piano",
      "caption": "Organ 2 Rows",
      "nStrings": 2,
      "rowRange": [48, 36],
      "frets": 49,
      "nut": false,
      "reverse": false,
      "pianoNamesRow": false,
      "pianoSkeuomorphic": true,
      "fixedFretWidthMult": 0.5
    },
    {
      "instance": false,
      "baseID": "Organ3Rows",
      "baseInstrument": "Piano",
      "caption": "Organ 3 Rows",
      "nStrings": 2,
      "rowRange": [48, 36, 24],
      "frets": 48,
      "nut": false,
      "reverse": false,
      "pianoNamesRow": false,
      "pianoSkeuomorphic": true,
      "fixedFretWidthMult": 0.5
    }
  ]
}
